### PR TITLE
Added function to generate and delete API key

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by rhaxma** [comment]
Do I need to use **SelfhostedGuard** in routes?

**Review by kruzhambus — COMMENTED** [review]
add a lines to user.controller.ts(post and delete) like "this.logger.log({ user_id }, 'POST /user/api-key')"

**Comment by rhaxma** [comment]
An `Unauthorized` error occurs when trying to delete a user's API key.

**Comment by kruzhambus** [comment]
Because Nest js call method [DELETE /user/:id]
and write /api-key like id 
{
  "id": "api-key",
  "uid": "0d67fc35-d792-4792-9fd7-2d073c376def"
}

**Comment by kruzhambus** [comment]
You can be fixed if you move the code above its method [DELETE /user/:id]
But I think this is a bad decision

**Review by kruzhambus — APPROVED** [review]

**Review by Blaumaus — APPROVED** [review]

**Pull request merged**
